# Generated by Django 3.1.12 on 2021-06-15 04:50

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Title')),
                ('picture', models.ImageField(help_text='The ideal dimension is 84x84. The max size is 2 MB.', upload_to='uploads/authors/pictures/', verbose_name='Thumb')),
                ('additional_information', models.CharField(max_length=200, verbose_name='Additional Information')),
                ('is_active', models.BooleanField(verbose_name='Is Active?')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=125, verbose_name='Category')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('summary', models.TextField(verbose_name='Summary')),
                ('content', ckeditor.fields.RichTextField()),
                ('is_active', models.BooleanField(verbose_name='Is Active?')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated At')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='challenge.author', verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
