# Generated by Django 3.1.12 on 2021-06-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='picture',
            field=models.ImageField(help_text='The ideal dimension is 84x84. The max size is 2 MB.', upload_to='uploads/authors/pictures/', verbose_name='Picture'),
        ),
    ]
